- name: show kernel shared memeory of compute
  ignore_errors: True
  shell:
    cat /sys/kernel/mm/ksm/run;
  args:
    executable: /bin/bash
  register: cmd
- debug: var=cmd.stdout_lines
- debug: var=cmd.stderr_lines
