---
##############################################################################
# Copyright (c) 2017 Huawei Technologies Co.,Ltd and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: create flavor yardstick-pinned-flavor
  shell:
    source /etc/yardstick/openstack.creds;
    nova flavor-create 'yardstick-pinned-flavor' $(cat /proc/sys/kernel/random/uuid) 512 3 2;
    nova flavor-list
  args:
    executable: /bin/bash

- name: set yardstick-pinned-flavor property
  shell:
    source /etc/yardstick/openstack.creds;
    openstack flavor set --property hw:cpu_policy=dedicated yardstick-pinned-flavor;
    openstack flavor set --property hw:numa_nodes=1 yardstick-pinned-flavor;
  args:
      executable: /bin/bash
