- name: show RAM allocation ratio of compute
  ignore_errors: True
  shell:
    cat /etc/nova/nova.conf | grep 'ram_allocation_ratio' || echo 'ERROR';
  args:
    executable: /bin/bash
  register: cmd
- debug: var=cmd.stdout_lines
- debug: var=cmd.stderr_lines
