- name: set flv_dedicated_compute property
  shell:
    source /etc/yardstick/openstack.creds;
    openstack --insecure flavor set --property hw:numa_nodes=1 test_dedicated_compute;
    openstack --insecure flavor show test_dedicated_compute;
  args:
      executable: /bin/bash
  register: cmd
- debug: var=cmd.stdout_lines

- name: create VM
  shell:
    source /etc/yardstick/openstack.creds;
    export vm_name=test_vm_$RANDOM;
    openstack --insecure server create --flavor test_dedicated_compute --image centos_yardstick --nic net-id=ext-net  \
    --security-group sg_yardstick --key key_yardstick $vm_name;
    openstack --insecure server list | grep $vm_name | awk '{print $2}';
  args:
      executable: /bin/bash
  register: vm_id
- debug: var=vm_id.stdout_lines

