- name: show huge page of compute
  ignore_errors: True
  shell:
    cat /proc/meminfo | grep -i Huge || echo 'ERROR';
  args:
    executable: /bin/bash
  register: cmd
- debug: var=cmd.stdout_lines
- debug: var=cmd.stderr_lines
