- name: create VM
  shell:
    source /etc/yardstick/openstack.creds;
    export vm1_name=test_vm1_$RANDOM;
    export vm2_name=test_vm2_$RANDOM;
    echo $vm1_name;
    echo $vm2_name;
    openstack --insecure server create --flavor test_dedicated_compute --image centos_yardstick --nic net-id=ext-net  \
    --security-group sg_yardstick --key key_yardstick $vm1_name;
    openstack --insecure server create --flavor test_dedicated_compute --image centos_yardstick --nic net-id=ext-net  \
    --security-group sg_yardstick --key key_yardstick $vm2_name;
  args:
    executable: /bin/bash
  register: o_create_vm
- debug: var=o_create_vm.stdout_lines

- name: get VM IP
  shell:
    sleep 40;
    source /etc/yardstick/openstack.creds;
    openstack --insecure server show {{ o_create_vm.stdout_lines[0] }} | grep address | awk -F '|' '{print $3}' | awk -F "=" '{print $2}' | xargs;
    openstack --insecure server show {{ o_create_vm.stdout_lines[1] }} | grep address | awk -F '|' '{print $3}' | awk -F "=" '{print $2}' | xargs;
  args:
    executable: /bin/bash
  register: o_vm_ip
- debug: var=o_vm_ip.stdout_lines

- name: connect to VM1 and ping VM2
  ignore_errors: True
  shell:
    ssh -i /etc/yardstick/ssh/id_rsa -F /etc/yardstick/ssh/ssh_config root@{{ o_vm_ip.stdout_lines[0] }} \
    'ifconfig' || echo 'ERROR';
    echo ------------------------------------------------------------------------------------------------------;
    sleep 20;
    ssh -i /etc/yardstick/ssh/id_rsa -F /etc/yardstick/ssh/ssh_config root@{{ o_vm_ip.stdout_lines[1] }} \
    'ifconfig' || echo 'ERROR';
    echo ------------------------------------------------------------------------------------------------------;
    ssh -i /etc/yardstick/ssh/id_rsa -F /etc/yardstick/ssh/ssh_config root@{{ o_vm_ip.stdout_lines[0] }} \
    'ping -c 3 {{ o_vm_ip.stdout_lines[1] }}' || echo 'ERROR';
  args:
    executable: /bin/bash
  register: cmd
- debug: var=cmd.stdout_lines
- debug: var=cmd.stderr_lines

