---                                                                                                                                                                                        
##############################################################################
# Copyright (c) 2017 Huawei Technologies Co.,Ltd and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: localhost
  roles:
    - role: dedicated_ansible_compute

- hosts: localhost
  roles:
    - role: cmri_ansible_5_1_2_7_1

- hosts: Compute
  roles:
    - role: cmri_ansible_5_1_2_7_2

- hosts: localhost
  roles:
    - role: cmri_ansible_5_1_2_7_3

