- name: create VM
  shell:
    source /etc/yardstick/openstack.creds;
    export vm_name=test_vm_$RANDOM;
    echo $vm_name;
    openstack --insecure server create --flavor yardstick-flavor --image centos_yardstick --nic net-id=ext-net  --security-group sg_yardstick --key key_yardstick $vm_name;
  args:
    executable: /bin/bash
  register: o_create_vm
- debug: var=o_create_vm.stdout_lines

- name: create new volume
  shell:
    source /etc/yardstick/openstack.creds;
    export vol_name=test_vol_$RANDOM;
    echo $vol_name;
    openstack --insecure volume create --size 5 $vol_name;
  args:
    executable: /bin/bash
  register: o_create_vol
- debug: var=o_create_vol.stdout_lines

- name: add new volume to server
  shell:
    sleep 20;
    source /etc/yardstick/openstack.creds;
    openstack --insecure server add volume {{ o_create_vm.stdout_lines[0] }} {{ o_create_vol.stdout_lines[0] }};
    openstack --insecure volume list;
  args:
    executable: /bin/bash
  register: o_add_vol
- debug: var=o_add_vol.stdout_lines

- name: get VM IP
  shell:
    sleep 40;
    source /etc/yardstick/openstack.creds;
    openstack --insecure server show {{ o_create_vm.stdout_lines[0] }} | grep address | awk -F '|' '{print $3}' | awk -F "=" '{print $2}' | xargs;
  args:
      executable: /bin/bash
  register: o_show_vm
- debug: var=o_show_vm.stdout_lines

- name: write to volume and show it
  shell:
    ssh -i /etc/yardstick/ssh/id_rsa -F /etc/yardstick/ssh/ssh_config root@{{ o_show_vm.stdout_lines[0] }} \
    'mkfs.ext4 /dev/vdb; mount /dev/vdb /mnt; echo "That is what you wrote to volume!" > /mnt/test; cat /mnt/test;' || echo 'ERROR';
  args:
      executable: /bin/bash
  register: cmd
- debug: var=cmd.stdout_lines

- name: remove volume to server
  shell:
    source /etc/yardstick/openstack.creds;
    openstack --insecure server remove volume {{ o_create_vm.stdout_lines[0] }} {{ o_create_vol.stdout_lines[0] }};
    openstack --insecure volume list;
  args:
    executable: /bin/bash

- name: delete volume
  shell:
    sleep 30;
    source /etc/yardstick/openstack.creds;
    openstack --insecure volume delete {{ o_create_vol.stdout_lines[0] }}
  args:
    executable: /bin/bash
  ignore_errors: True

- name: delete VM
  shell:
    source /etc/yardstick/openstack.creds;
    openstack --insecure server delete {{ o_create_vm.stdout_lines[0] }};
  args:
      executable: /bin/bash


